language: cpp

services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false
  slack: aices-pcm-cfd:ShncJAFCJzx48zt8hrXpRwGw

before_install:
- docker pull zimmerman/nsb-pcm:latest

script:
- echo $TRAVIS_COMMIT
- docker run -e TRAVIS_COMMIT=$TRAVIS_COMMIT -P -v `pwd`:/home/nsb-pcm:rw zimmerman/nsb-pcm /bin/sh -c "cd nsb-pcm; git pull; git checkout $TRAVIS_COMMIT; cd build; cmake ..; make; ctest -j2"
