language: cpp

services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false
  slack: aices-pcm-cfd:ShncJAFCJzx48zt8hrXpRwGw

before_install:
- docker pull dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease

script:
- docker run -P -v `pwd`:/home/dealii/phaseflow-dealii:rw dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease /bin/sh -c "mkdir build; cd build; cmake ../phaseflow-dealii; make release; ctest -j2"
