language: cpp

services:
  - docker

notifications:
  email: false

before_install:
- docker pull zimmerman/nsb-pcm

script:
- docker run -P -v "cd nsb-pcm; git pull; cd build; cmake ..; make -j2"
- docker run -P -v "cd nsb-pcm; git pull; cd build; cmake ..; ctest -j2"
