language: cpp

services:
  - docker

branches:
    only:
        -master
  
notifications:
  email: false
  slack: aices-pcm-cfd:ShncJAFCJzx48zt8hrXpRwGw

before_install:
- docker pull zimmerman/nsb-pcm

script:
- docker run -P -v `pwd`:/home/nsb-pcm:rw zimmerman/nsb-pcm /bin/sh -c "cd nsb-pcm; git pull; cd build; cmake ..; make -j2"
- docker run -P -v `pwd`:/home/nsb-pcm:rw zimmerman/nsb-pcm /bin/sh -c "cd nsb-pcm/build; ctest -j2"
