language: cpp

services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false
  slack: aices-pcm-cfd:ShncJAFCJzx48zt8hrXpRwGw

before_install:
- docker pull zimmerman/nsb-pcm:latest

script:
- docker run -P -v `pwd`:/home/nsb-pcm:rw zimmerman/nsb-pcm /bin/sh -c "cd nsb-pcm; git checkout master; git pull; cd build; cmake ..; make; ctest -j2"
