language: cpp

services:
  - docker

branches:
    only:
        - master
  
notifications:
  email: false
  slack: aices-pcm-cfd:ShncJAFCJzx48zt8hrXpRwGw

before_install:
- docker pull dealii/dealii:v8.5.0-gcc-mpi-fulldepscandi-debugrelease

script:
- docker run -P -v `pwd`:/home/dealii/nsb-pcm:rw dealii/dealii:v8.5.0-gcc-mpi-fulldepscandi-debugrelease /bin/sh -c "cd nsb-pcm; mkdir build; cd build; cmake ..; make; ctest -j2"
